config {
    type: "incremental",
    protected: true,
    schema: "trusted",
    description: "A trusted dataset derived from the raw.tb_sih_rd table, containing clean and structured hospital admission data from the SUS Hospital Information System (SIH)",
    tags: ["sih_rd"],
    columns: {
        municipality_code: "Code of the municipality associated with the data record",
        date: "The specific date of the hospital admission or procedure",
        year: "The year when the event occurred",
        month: "The month when the event occurred",
        specialty_bed: "AIH specialty, according to the Specialty Table",
        aih: "Authorization for Hospital Admission (AIH) identifier",
        type_aih: "Type of the AIH",
        patient_municipality: "The municipality where the patient resides",
        gender: "The gender of the patient",
        type_uti: "Type of intensive care unit (ICU) the patient used",
        days_hospitalized: "The total number of days the patient was hospitalized",
        procedure: "The medical procedure performed during hospitalization",
        total_value: "The total cost associated with the hospitalization",
        death: "Indicates if the patient passed away during the hospitalization",
        risk_pregnant: "Specifies if the patient was at risk during pregnancy",
        race_color: "The race or color category of the patient",
        birth_date: "The birth date of the patient",
        age: "The age of the patient at the time of the event",
        date_loading: "Timestamp indicating when the data was loaded into the database"
    },
    assertions: {
        uniqueKey: ["aih", "date"],
        nonNull: ["aih", "specialty_bed", "procedure"],
        rowConditions: [
            'LENGTH(municipality_code) = 6',
            'LENGTH(aih) = 13'
        ]
    },
    bigquery: {
        partitionBy: "date",
        updatePartitionFilter: "date >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)"
  },
}

  -- Defining the columns to be used in the project and the data type of each one
SELECT
  UF_ZI                                                                   AS municipality_code,
  SAFE_CAST(CONCAT(ANO_CMPT, "-", LPAD(MES_CMPT, 2, "0"), "-01") AS DATE) AS date,
  ANO_CMPT                                                                AS year,
  MES_CMPT                                                                AS month,
  ESPEC                                                                   AS specialty_bed,
  N_AIH                                                                   AS aih,
  IDENT                                                                   AS type_aih,
  MUNIC_RES                                                               AS patient_municipality,
  SEXO                                                                    AS gender,
  MARCA_UTI                                                               AS type_uti,
  CAST(QT_DIARIAS AS INT64)                                               AS days_hospitalized,
  PROC_REA                                                                AS procedure,
  CAST(VAL_TOT AS FLOAT64)                                                AS total_value,
  MORTE                                                                   AS death,
  GESTRISCO                                                               AS risk_pregnant,
  RACA_COR                                                                AS race_color,
  SAFE_CAST(PARSE_DATE('%Y%m%d', NASC) AS DATE)                           AS birth_date,
  DATE_DIFF(CURRENT_DATE("America/Sao_Paulo"),
    SAFE_CAST(PARSE_DATE('%Y%m%d', NASC) AS DATE), YEAR)                  AS age,
  TIMESTAMP(CURRENT_DATETIME("America/Sao_Paulo"))                        AS date_loading
FROM
  ${ref("raw", "tb_sih_rd")}

${when(incremental(), `WHERE TIMESTAMP(date_loading) > (SELECT MAX(date_loading) FROM ${self()})`) }
